# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd8d6c9fba85395385900ddf0d6e96ee2088d93dfed77dc159350226824c970f6b01147de714942fed56374de34bb49ec710d957a58e562f98f24e1b3ba1f62

test:
  secret_key_base: 64eecb02bf189bd8e2b848563a76a06b1432ef8fab567501a4227ce6ed28702942a80589786f51dad677173b53462a849a9ca30a21f036e93553f4f1b073ab36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
